### ISSUE TITLE
Docker image way out of date

### ISSUE THREAD

**Issue by dtcooper** [benas/ssed#2]
Heya! Couldn't get apk to run on it because Alpine was so old. Would it be possible to bump it? Thanks!

**Comment by fmbenhassine** [comment]
Hi @dtcooper ,

Thank you for raising this. Which Alpine are you referring to? Are you referring to the current base image `google/golang:stable` which is indeed obsolete? 

FYI, I updated the base image to the official `golang:latest` and the build is successful, see 49386c1. Is this what you're asking for?

**Comment by dtcooper** [comment]
Yes! That's perfect. Honestly any version where apk still works and doesn't die with unavailable package indexes is great. Thank you.
